#include<iostream>
using namespace std;

int main()
{
  int a =10;
  int b = 0;

  try{
       if(b == 0)throw 0;
       //unsure logic or code here
  cout<<a/b<<endl;
  }
  catch(...){
      cout<<"thrown from the try block.!"<<endl;
  }


 //catch(int e){
 //    cout<<e<<"thrown from the try block.!"<<endl;
 //    alternative code or logic.!
 // }

 // catch(char err){
 //     cout<<err<<"thrown from the try block.!"<<endl;
 //}

  cout<<"Program ended normally"<<endl;
  return 0;
}
